### ISSUE TITLE
Error parsing Leiden+ 

### ISSUE THREAD

**Issue by jnussbaum** [papyri/xsugar#21] opened 2020-07-27 12:19 UTC
Some papyri have a correct Leiden+ and correct XML, which is correctly displayed on papyri.info. But when editing their Leiden+ code, they produce an error at a position which was not edited. This happened to me with several different papyri. So it is impossible to edit these papyri (except taking the workaround via xml code). Apparently, this must be a Leiden+ <-> XML parsing error.

## Steps to reproduce the error

1. Navigate to http://papyri.info/ddbdp/p.cair.masp;1;67109
2. Click on "open in editor"
3. Click on DDbDP > Leiden+
4. Click on "Save" (without making any changes to the Leiden+ !!!)
5. You will get an error on line 8: Διοσκόρου υ ἱ̣(¨)ο**POSSIBLE ERROR**ῦ αὐτοῦ

**Comment by jcowey** [comment] 2020-07-27 13:34
This is another description of behaviour described in #17

**Comment by ryanfb** [comment] 2021-02-24 16:50
Closing as duplicate of #17

**Closed by ryanfb** 2021-02-24 16:50 UTC
